# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - './.docker/mongo:/data/db'
      - './.docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
